---
# defaults file for /etc/ansible/roles/Jenkins

- hosts: localhost
  become: yes

  tasks:
    - name: Get Jenkins Repo
      get_url:
         url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
         dest: /etc/yum.repos.d/jenkins.repo
    - name: Import RPM key
      rpm_key:
          key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Yum install Jenkins
      yum:
         name: jenkins
         state: latest



